version: 2
updates:
- package-ecosystem: pnpm
  directory: "/"
  schedule:
    interval: weekly
  target-branch: dev
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  target-branch: dev
- package-ecosystem: pnpm
  directory: "/tests/"
  schedule:
    interval: weekly
  target-branch: dev
- package-ecosystem: bundler
  directory: "/tests/"
  schedule:
    interval: weekly
  target-branch: dev
