recaptcha:
  key: '6LdcuiAUAAAAAL7xHfw3gTz603bDtSlzBo1DO9lx'
  secret: '6LdcuiAUAAAAAMCixgeP0f4AGjIaV0Y1UTRenMRp'
  encrypted_secret: 'SdJ7ib962U9rgDdzcXpyeKpfPqDZLNqV3UzEhGD0TEXJqwdCrjhGtFqtnPkJRC2IUnGfhUQGnlvC9OC+F+XU15LGrymiieA9sSQTTxSVDHwq4kE/EAzDkgBhWqi396WVmRvdmKnpoFQ7Rj+CdL8K+mYtTDx/+/pvax0vlkoX+oU='

dareboost:
  monitoring : 7134
  token: 59ba585f0cf2502fdb8f4697

algolia:
  application_id: '97EL687MDM'
  index_name: 'jekyll'
  read_only_api_key: '45e74dfb46facf8ee7f3038c305a9a7e'
  excluded_files:
    - 404.html
    - index.html
  settings:
    attributesToIndex:
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(slug)
